# Generated by Django 3.1.3 on 2022-08-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='context',
            new_name='content',
        ),
    ]
